# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cf15053c97e794faeb492035cb80ce8a"
name = "Sneaker Cleaning Manager "
application_url = "https://cable-evolution-cancellation-circulation.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders/create"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,write_draft_orders,write_files,write_orders,write_products"

[auth]
redirect_urls = [
  "https://cable-evolution-cancellation-circulation.trycloudflare.com/api/auth"
]

[app_proxy]
url = "https://cable-evolution-cancellation-circulation.trycloudflare.com"
subpath = "sneaker-cleaning-dev"
prefix = "apps"
